"use strict";

/**
JS mirror of `contracts/production/libraries/CosmicSignatureConstants.sol`.
Only constants the fuzz `GameModel` needs are mirrored.
Keep in sync with the Solidity source; the fuzz test asserts the on-chain initialization values
against these during model initialization, so a drift fails fast.
*/

const MICROSECONDS_PER_SECOND = 1_000_000n;

const SECONDS_PER_HOUR = 3_600n;
const SECONDS_PER_DAY = 24n * SECONDS_PER_HOUR;

const DEFAULT_DELAY_DURATION_BEFORE_ROUND_ACTIVATION = SECONDS_PER_HOUR / 2n;
const INITIAL_MAIN_PRIZE_TIME_INCREMENT = SECONDS_PER_HOUR;
const DEFAULT_ETH_DUTCH_AUCTION_DURATION_DIVISOR =
	(INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + (2n * SECONDS_PER_DAY) / 2n) / (2n * SECONDS_PER_DAY);
const FIRST_ROUND_INITIAL_ETH_BID_PRICE = 10n ** 14n; // 0.0001 ether
const ETH_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER = 2n;
const DEFAULT_ETH_DUTCH_AUCTION_ENDING_BID_PRICE_DIVISOR = 100n * ETH_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER;
const DEFAULT_ETH_BID_PRICE_INCREASE_DIVISOR = 100n;
const RANDOMWALK_NFT_BID_PRICE_DIVISOR = 2n;
const DEFAULT_ETH_BID_REFUND_AMOUNT_IN_GAS_TO_SWALLOW_MAX_LIMIT = 6_843n;
const INITIAL_CST_DUTCH_AUCTION_DURATION = SECONDS_PER_DAY / 2n;
const DEFAULT_CST_DUTCH_AUCTION_DURATION_DIVISOR =
	(INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + INITIAL_CST_DUTCH_AUCTION_DURATION / 2n) / INITIAL_CST_DUTCH_AUCTION_DURATION;
const DEFAULT_CST_DUTCH_AUCTION_DURATION_CHANGE_DIVISOR = 250n;
const CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER = 2n;
const DEFAULT_CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MIN_LIMIT = 200n * 10n ** 18n;
const DEFAULT_BID_MESSAGE_LENGTH_MAX_LIMIT = 280n;
const DEFAULT_BID_CST_REWARD_AMOUNT = 100n * 10n ** 18n;
const DEFAULT_BID_CST_REWARD_AMOUNT_MULTIPLIER =
	3n * (10n ** 18n) ** 2n * INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND;
const DEFAULT_CST_PRIZE_AMOUNT = 1_000n * 10n ** 18n;
const DEFAULT_CHRONO_WARRIOR_ETH_PRIZE_AMOUNT_PERCENTAGE = 8n;
const DEFAULT_RAFFLE_TOTAL_ETH_PRIZE_AMOUNT_FOR_BIDDERS_PERCENTAGE = 4n;
const DEFAULT_NUM_RAFFLE_ETH_PRIZES_FOR_BIDDERS = 3n;
const DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_BIDDERS = 10n;
const DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_RANDOMWALK_NFT_STAKERS = 10n;
const DEFAULT_COSMIC_SIGNATURE_NFT_STAKING_TOTAL_ETH_REWARD_AMOUNT_PERCENTAGE = 6n;
const DEFAULT_INITIAL_DURATION_UNTIL_MAIN_PRIZE_DIVISOR =
	(INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + SECONDS_PER_DAY / 2n) / SECONDS_PER_DAY;
const DEFAULT_MAIN_PRIZE_TIME_INCREMENT_INCREASE_DIVISOR = 100n;
const DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE = SECONDS_PER_DAY;
const DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE_V2 = 2n * SECONDS_PER_DAY;
const DEFAULT_MAIN_ETH_PRIZE_AMOUNT_PERCENTAGE = 25n;
const COSMIC_SIGNATURE_NFT_NFT_NAME_LENGTH_MAX_LIMIT = 32n;
const RANDOMWALK_NFT_NAME_LENGTH_MAX_LIMIT = 32n;
const DEFAULT_TIMEOUT_DURATION_TO_WITHDRAW_PRIZES = 5n * 7n * SECONDS_PER_DAY;
const DEFAULT_MARKETING_WALLET_CST_CONTRIBUTION_AMOUNT = 3_000n * 10n ** 18n;
const DEFAULT_CHARITY_ETH_DONATION_AMOUNT_PERCENTAGE = 7n;
const TIMESTAMP_9000_01_01 = 221_845_392_000n;

// `RandomWalkNFT`-specific.
const RANDOMWALK_NFT_PRICE_INCREASE_NUMERATOR = 10_011n;
const RANDOMWALK_NFT_PRICE_INCREASE_DENOMINATOR = 10_000n;
const RANDOMWALK_NFT_WITHDRAWAL_WAIT_SECONDS = 30n * SECONDS_PER_DAY;

// DAO.
const DAO_DEFAULT_VOTING_DELAY = 2n * SECONDS_PER_DAY;
const DAO_DEFAULT_VOTING_PERIOD = 2n * 7n * SECONDS_PER_DAY;

module.exports = {
	MICROSECONDS_PER_SECOND,
	SECONDS_PER_HOUR,
	SECONDS_PER_DAY,
	DEFAULT_DELAY_DURATION_BEFORE_ROUND_ACTIVATION,
	INITIAL_MAIN_PRIZE_TIME_INCREMENT,
	DEFAULT_ETH_DUTCH_AUCTION_DURATION_DIVISOR,
	FIRST_ROUND_INITIAL_ETH_BID_PRICE,
	ETH_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER,
	DEFAULT_ETH_DUTCH_AUCTION_ENDING_BID_PRICE_DIVISOR,
	DEFAULT_ETH_BID_PRICE_INCREASE_DIVISOR,
	RANDOMWALK_NFT_BID_PRICE_DIVISOR,
	DEFAULT_ETH_BID_REFUND_AMOUNT_IN_GAS_TO_SWALLOW_MAX_LIMIT,
	INITIAL_CST_DUTCH_AUCTION_DURATION,
	DEFAULT_CST_DUTCH_AUCTION_DURATION_DIVISOR,
	DEFAULT_CST_DUTCH_AUCTION_DURATION_CHANGE_DIVISOR,
	CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER,
	DEFAULT_CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MIN_LIMIT,
	DEFAULT_BID_MESSAGE_LENGTH_MAX_LIMIT,
	DEFAULT_BID_CST_REWARD_AMOUNT,
	DEFAULT_BID_CST_REWARD_AMOUNT_MULTIPLIER,
	DEFAULT_CST_PRIZE_AMOUNT,
	DEFAULT_CHRONO_WARRIOR_ETH_PRIZE_AMOUNT_PERCENTAGE,
	DEFAULT_RAFFLE_TOTAL_ETH_PRIZE_AMOUNT_FOR_BIDDERS_PERCENTAGE,
	DEFAULT_NUM_RAFFLE_ETH_PRIZES_FOR_BIDDERS,
	DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_BIDDERS,
	DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_RANDOMWALK_NFT_STAKERS,
	DEFAULT_COSMIC_SIGNATURE_NFT_STAKING_TOTAL_ETH_REWARD_AMOUNT_PERCENTAGE,
	DEFAULT_INITIAL_DURATION_UNTIL_MAIN_PRIZE_DIVISOR,
	DEFAULT_MAIN_PRIZE_TIME_INCREMENT_INCREASE_DIVISOR,
	DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE,
	DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE_V2,
	DEFAULT_MAIN_ETH_PRIZE_AMOUNT_PERCENTAGE,
	COSMIC_SIGNATURE_NFT_NFT_NAME_LENGTH_MAX_LIMIT,
	RANDOMWALK_NFT_NAME_LENGTH_MAX_LIMIT,
	DEFAULT_TIMEOUT_DURATION_TO_WITHDRAW_PRIZES,
	DEFAULT_MARKETING_WALLET_CST_CONTRIBUTION_AMOUNT,
	DEFAULT_CHARITY_ETH_DONATION_AMOUNT_PERCENTAGE,
	TIMESTAMP_9000_01_01,
	RANDOMWALK_NFT_PRICE_INCREASE_NUMERATOR,
	RANDOMWALK_NFT_PRICE_INCREASE_DENOMINATOR,
	RANDOMWALK_NFT_WITHDRAWAL_WAIT_SECONDS,
	DAO_DEFAULT_VOTING_DELAY,
	DAO_DEFAULT_VOTING_PERIOD,
};
