[package]
name = "rust_3body"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"        # Latest version
rayon = "1.8.1"            # Updated to the latest version
sha3 = "0.10.8"            # Updated to the latest version
clap = { version = "4.5.4", features = ["derive"] } # Updated
hex = "0.4.3"              # Latest version
image = "0.25.1"           # Updated to the latest version
imageproc = "0.24.0"       # Updated to the latest version
palette = "0.7.3"          # Updated to the latest version
rustfft = "6.1.0"          # Updated to the latest version
statrs = "0.16.0"          # Still latest, unchanged
kiddo = "5.0.1"            # Already up-to-date

[profile.release]
lto = true
codegen-units = 1
panic = "abort"