[package]
name         = "three_body_problem"
version      = "1.0.0"
edition      = "2024"
rust-version = "1.86.0"

[dependencies]
clap     = { version = "4.5.37", features = ["derive"] }
hex      = "0.4.3"
image    = "0.25.6"
nalgebra = "0.33.2"
palette  = "0.7.6"
rayon    = "1.10.0"
rustfft  = "6.3.0"
sha3     = "0.10.8"
statrs   = "0.18.0"
once_cell = "1.19.0"

[profile.release]
opt-level       = 3
lto             = "fat"
codegen-units   = 1
panic           = "abort"
incremental     = false