[package]
name = "rust_3body"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29.0"
plotters = "0.3.1"
image = "0.23"
imageproc = "0.22"
rustfft = "6.1.0"
statrs = "0.16.0"
rayon = "1.5"
palette = "0.6.0"
sha3 = "0.9"
hex = "0.4"
digest = "0.9"
clap = { version = "4.2", features = ["derive"]}
noise = "0.8"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
