"use strict";

// JavaScript mirrors of `CosmicSignatureConstants.sol`.

const DEFAULT_DELAY_DURATION_BEFORE_ROUND_ACTIVATION = (60n * 60n) / 2n;
const TIMESTAMP_9000_01_01 = 221_845_392_000n;
const INITIAL_ROUND_ACTIVATION_TIME = TIMESTAMP_9000_01_01;
const INITIAL_ETH_DUTCH_AUCTION_DURATION = 2n * 24n * 60n * 60n;
const INITIAL_MAIN_PRIZE_TIME_INCREMENT = 60n * 60n;
const THOUSAND = 1000n;
const MILLION = THOUSAND * THOUSAND;
const MICROSECONDS_PER_SECOND = MILLION;
const DEFAULT_ETH_DUTCH_AUCTION_DURATION_DIVISOR = (INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + INITIAL_ETH_DUTCH_AUCTION_DURATION / 2n) / INITIAL_ETH_DUTCH_AUCTION_DURATION;
const FIRST_ROUND_INITIAL_ETH_BID_PRICE = 10n ** 14n;
const ETH_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER = 2n;
const DEFAULT_ETH_DUTCH_AUCTION_ENDING_BID_PRICE_DIVISOR = 100n * ETH_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER;
const DEFAULT_ETH_BID_PRICE_INCREASE_DIVISOR = 100n;
const RANDOMWALK_NFT_BID_PRICE_DIVISOR = 2n;
const DEFAULT_ETH_BID_REFUND_AMOUNT_IN_GAS_TO_SWALLOW_MAX_LIMIT = 6843n;
const INITIAL_CST_DUTCH_AUCTION_DURATION = (24n * 60n * 60n) / 2n;
const DEFAULT_CST_DUTCH_AUCTION_DURATION_DIVISOR = (INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + INITIAL_CST_DUTCH_AUCTION_DURATION / 2n) / INITIAL_CST_DUTCH_AUCTION_DURATION;
const DEFAULT_CST_DUTCH_AUCTION_DURATION_CHANGE_DIVISOR = 250n;
const CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER = 2n;
const DEFAULT_BID_CST_REWARD_AMOUNT = 100n * 10n ** 18n;
const DEFAULT_CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MIN_LIMIT = 2n * DEFAULT_BID_CST_REWARD_AMOUNT;
const INITIAL_BID_CST_REWARD_AMOUNT_PER_MINUTE = 10n ** 18n;
const DEFAULT_CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MIN_LIMIT_V3 = INITIAL_BID_CST_REWARD_AMOUNT_PER_MINUTE;
const DEFAULT_BID_CST_REWARD_AMOUNT_MULTIPLIER = (INITIAL_BID_CST_REWARD_AMOUNT_PER_MINUTE * INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + 60n / 2n) / 60n;
const INITIAL_CST_BID_PRICE_DECLINE_MULTIPLIER = (DEFAULT_BID_CST_REWARD_AMOUNT_MULTIPLIER + INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND / 2n) / (INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND);
const DEFAULT_CST_BID_PRICE_DECLINE_MULTIPLIER_CHANGE_DIVISOR = 100n;
const INITIAL_ROUND_LATE_BID_DURATION = 20n * 60n;
const DEFAULT_ROUND_LATE_BID_DURATION_DIVISOR = (INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + INITIAL_ROUND_LATE_BID_DURATION / 2n) / INITIAL_ROUND_LATE_BID_DURATION;
const ROUND_LATE_BID_PRICE_PREMIUM_AMOUNT_RESOLUTION_EXPONENT = 13n;
const DEFAULT_ROUND_LATE_BID_PRICE_PREMIUM_AMOUNT_BASE_MULTIPLIER = 3567993n << ROUND_LATE_BID_PRICE_PREMIUM_AMOUNT_RESOLUTION_EXPONENT;
const DEFAULT_ROUND_LATE_BID_PRICE_PREMIUM_AMOUNT_EXPONENT = 8n;
const DEFAULT_BID_MESSAGE_LENGTH_MAX_LIMIT = 280n;
const DEFAULT_BID_CST_REWARD_AMOUNT_RADICAND_MULTIPLIER = 3n * (10n ** 18n) ** 2n * INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND;
const DEFAULT_CST_PRIZE_AMOUNT = 1_000n * 10n ** 18n;
const DEFAULT_CHRONO_WARRIOR_ETH_PRIZE_AMOUNT_PERCENTAGE = 8n;
const DEFAULT_CHRONO_WARRIOR_ETH_PRIZE_AMOUNT_PERCENTAGE_V3 = 15n;
const DEFAULT_RAFFLE_TOTAL_ETH_PRIZE_AMOUNT_FOR_BIDDERS_PERCENTAGE = 4n;
const DEFAULT_RAFFLE_TOTAL_ETH_PRIZE_AMOUNT_FOR_BIDDERS_PERCENTAGE_V3 = 5n;
const DEFAULT_NUM_RAFFLE_ETH_PRIZES_FOR_BIDDERS = 3n;
const DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_BIDDERS = 10n;
const DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_RANDOMWALK_NFT_STAKERS = 10n;
const DEFAULT_COSMIC_SIGNATURE_NFT_STAKING_TOTAL_ETH_REWARD_AMOUNT_PERCENTAGE = 6n;
const DEFAULT_COSMIC_SIGNATURE_NFT_STAKING_TOTAL_ETH_REWARD_AMOUNT_PERCENTAGE_V3 = 5n;
const DEFAULT_INITIAL_DURATION_UNTIL_MAIN_PRIZE_DIVISOR = (INITIAL_MAIN_PRIZE_TIME_INCREMENT * MICROSECONDS_PER_SECOND + (24n * 60n * 60n) / 2n) / (24n * 60n * 60n);
const DEFAULT_MAIN_PRIZE_TIME_INCREMENT_INCREASE_DIVISOR = 100n;
const DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE = 24n * 60n * 60n;
const DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE_V2 = 2n * 24n * 60n * 60n;
const DEFAULT_MAIN_ETH_PRIZE_AMOUNT_PERCENTAGE = 25n;
const DEFAULT_MAIN_ETH_PRIZE_AMOUNT_PERCENTAGE_V3 = 20n;
const DEFAULT_MAIN_PRIZE_NUM_COSMIC_SIGNATURE_NFTS = 3n;
const COSMIC_SIGNATURE_NFT_NFT_NAME_LENGTH_MAX_LIMIT = 32n;
const COSMIC_SIGNATURE_NFT_DEFAULT_NFT_BASE_URI = "https://nfts.cosmicsignature.com/metadata/";
const COSMIC_SIGNATURE_NFT_DEFAULT_NFT_GENERATION_SCRIPT_URI = "ipfs://bafybeig7qgsl2c3hnxrt2mnbarestfzof7u3s3o2rw7c6fitryx3ruxora";
const DEFAULT_TIMEOUT_DURATION_TO_WITHDRAW_PRIZES = 5n * 7n * 24n * 60n * 60n;
const DEFAULT_MARKETING_WALLET_CST_CONTRIBUTION_AMOUNT = 3_000n * 10n ** 18n;
const DEFAULT_CHARITY_ETH_DONATION_AMOUNT_PERCENTAGE = 7n;
const DEFAULT_CHARITY_ETH_DONATION_AMOUNT_PERCENTAGE_V3 = 5n;
const DAO_DEFAULT_VOTING_DELAY = 2n * 24n * 60n * 60n;
const DAO_DEFAULT_VOTING_PERIOD = 2n * 7n * 24n * 60n * 60n;
const DAO_DEFAULT_PROPOSAL_THRESHOLD = DEFAULT_BID_CST_REWARD_AMOUNT;
const DAO_DEFAULT_VOTES_QUORUM_PERCENTAGE = 3n;
const BILLION = THOUSAND * MILLION;
const NANOSECONDS_PER_SECOND = BILLION;
const MILLISECONDS_PER_SECOND = THOUSAND;
const MINUTES_PER_HOUR = 60n;
const HOURS_PER_DAY = 24n;
const NANOSECONDS_PER_MINUTE = NANOSECONDS_PER_SECOND * 60n;
const NANOSECONDS_PER_HOUR = NANOSECONDS_PER_SECOND * (60n * 60n);
const NANOSECONDS_PER_DAY = NANOSECONDS_PER_SECOND * (24n * 60n * 60n);
const MICROSECONDS_PER_MINUTE = MICROSECONDS_PER_SECOND * 60n;
const MICROSECONDS_PER_HOUR = MICROSECONDS_PER_SECOND * (60n * 60n);
const MICROSECONDS_PER_DAY = MICROSECONDS_PER_SECOND * (24n * 60n * 60n);
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60n;
const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_SECOND * (60n * 60n);
const MILLISECONDS_PER_DAY = MILLISECONDS_PER_SECOND * (24n * 60n * 60n);

// Additional constants that do not exist in `CosmicSignatureConstants.sol`.
const SECONDS_PER_MINUTE = 60n;
const SECONDS_PER_HOUR = MINUTES_PER_HOUR * SECONDS_PER_MINUTE;
const SECONDS_PER_DAY = HOURS_PER_DAY * SECONDS_PER_HOUR;
const RANDOMWALK_NFT_NAME_LENGTH_MAX_LIMIT = 32n;
const RANDOMWALK_NFT_PRICE_INCREASE_NUMERATOR = 10_011n;
const RANDOMWALK_NFT_PRICE_INCREASE_DENOMINATOR = 10_000n;
const RANDOMWALK_NFT_WITHDRAWAL_WAIT_SECONDS = 30n * SECONDS_PER_DAY;

module.exports = {
	DEFAULT_DELAY_DURATION_BEFORE_ROUND_ACTIVATION,
	TIMESTAMP_9000_01_01,
	INITIAL_ROUND_ACTIVATION_TIME,
	INITIAL_ETH_DUTCH_AUCTION_DURATION,
	INITIAL_MAIN_PRIZE_TIME_INCREMENT,
	THOUSAND,
	MILLION,
	MICROSECONDS_PER_SECOND,
	DEFAULT_ETH_DUTCH_AUCTION_DURATION_DIVISOR,
	FIRST_ROUND_INITIAL_ETH_BID_PRICE,
	ETH_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER,
	DEFAULT_ETH_DUTCH_AUCTION_ENDING_BID_PRICE_DIVISOR,
	DEFAULT_ETH_BID_PRICE_INCREASE_DIVISOR,
	RANDOMWALK_NFT_BID_PRICE_DIVISOR,
	DEFAULT_ETH_BID_REFUND_AMOUNT_IN_GAS_TO_SWALLOW_MAX_LIMIT,
	INITIAL_CST_DUTCH_AUCTION_DURATION,
	DEFAULT_CST_DUTCH_AUCTION_DURATION_DIVISOR,
	DEFAULT_CST_DUTCH_AUCTION_DURATION_CHANGE_DIVISOR,
	CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MULTIPLIER,
	DEFAULT_BID_CST_REWARD_AMOUNT,
	DEFAULT_CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MIN_LIMIT,
	INITIAL_BID_CST_REWARD_AMOUNT_PER_MINUTE,
	DEFAULT_CST_DUTCH_AUCTION_BEGINNING_BID_PRICE_MIN_LIMIT_V3,
	DEFAULT_BID_CST_REWARD_AMOUNT_MULTIPLIER,
	INITIAL_CST_BID_PRICE_DECLINE_MULTIPLIER,
	DEFAULT_CST_BID_PRICE_DECLINE_MULTIPLIER_CHANGE_DIVISOR,
	INITIAL_ROUND_LATE_BID_DURATION,
	DEFAULT_ROUND_LATE_BID_DURATION_DIVISOR,
	ROUND_LATE_BID_PRICE_PREMIUM_AMOUNT_RESOLUTION_EXPONENT,
	DEFAULT_ROUND_LATE_BID_PRICE_PREMIUM_AMOUNT_BASE_MULTIPLIER,
	DEFAULT_ROUND_LATE_BID_PRICE_PREMIUM_AMOUNT_EXPONENT,
	DEFAULT_BID_MESSAGE_LENGTH_MAX_LIMIT,
	DEFAULT_BID_CST_REWARD_AMOUNT_RADICAND_MULTIPLIER,
	DEFAULT_CST_PRIZE_AMOUNT,
	DEFAULT_CHRONO_WARRIOR_ETH_PRIZE_AMOUNT_PERCENTAGE,
	DEFAULT_CHRONO_WARRIOR_ETH_PRIZE_AMOUNT_PERCENTAGE_V3,
	DEFAULT_RAFFLE_TOTAL_ETH_PRIZE_AMOUNT_FOR_BIDDERS_PERCENTAGE,
	DEFAULT_RAFFLE_TOTAL_ETH_PRIZE_AMOUNT_FOR_BIDDERS_PERCENTAGE_V3,
	DEFAULT_NUM_RAFFLE_ETH_PRIZES_FOR_BIDDERS,
	DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_BIDDERS,
	DEFAULT_NUM_RAFFLE_COSMIC_SIGNATURE_NFTS_FOR_RANDOMWALK_NFT_STAKERS,
	DEFAULT_COSMIC_SIGNATURE_NFT_STAKING_TOTAL_ETH_REWARD_AMOUNT_PERCENTAGE,
	DEFAULT_COSMIC_SIGNATURE_NFT_STAKING_TOTAL_ETH_REWARD_AMOUNT_PERCENTAGE_V3,
	DEFAULT_INITIAL_DURATION_UNTIL_MAIN_PRIZE_DIVISOR,
	DEFAULT_MAIN_PRIZE_TIME_INCREMENT_INCREASE_DIVISOR,
	DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE,
	DEFAULT_TIMEOUT_DURATION_TO_CLAIM_MAIN_PRIZE_V2,
	DEFAULT_MAIN_ETH_PRIZE_AMOUNT_PERCENTAGE,
	DEFAULT_MAIN_ETH_PRIZE_AMOUNT_PERCENTAGE_V3,
	DEFAULT_MAIN_PRIZE_NUM_COSMIC_SIGNATURE_NFTS,
	COSMIC_SIGNATURE_NFT_NFT_NAME_LENGTH_MAX_LIMIT,
	COSMIC_SIGNATURE_NFT_DEFAULT_NFT_BASE_URI,
	COSMIC_SIGNATURE_NFT_DEFAULT_NFT_GENERATION_SCRIPT_URI,
	DEFAULT_TIMEOUT_DURATION_TO_WITHDRAW_PRIZES,
	DEFAULT_MARKETING_WALLET_CST_CONTRIBUTION_AMOUNT,
	DEFAULT_CHARITY_ETH_DONATION_AMOUNT_PERCENTAGE,
	DEFAULT_CHARITY_ETH_DONATION_AMOUNT_PERCENTAGE_V3,
	DAO_DEFAULT_VOTING_DELAY,
	DAO_DEFAULT_VOTING_PERIOD,
	DAO_DEFAULT_PROPOSAL_THRESHOLD,
	DAO_DEFAULT_VOTES_QUORUM_PERCENTAGE,
	BILLION,
	NANOSECONDS_PER_SECOND,
	MILLISECONDS_PER_SECOND,
	MINUTES_PER_HOUR,
	HOURS_PER_DAY,
	NANOSECONDS_PER_MINUTE,
	NANOSECONDS_PER_HOUR,
	NANOSECONDS_PER_DAY,
	MICROSECONDS_PER_MINUTE,
	MICROSECONDS_PER_HOUR,
	MICROSECONDS_PER_DAY,
	MILLISECONDS_PER_MINUTE,
	MILLISECONDS_PER_HOUR,
	MILLISECONDS_PER_DAY,
	SECONDS_PER_MINUTE,
	SECONDS_PER_HOUR,
	SECONDS_PER_DAY,
	RANDOMWALK_NFT_NAME_LENGTH_MAX_LIMIT,
	RANDOMWALK_NFT_PRICE_INCREASE_NUMERATOR,
	RANDOMWALK_NFT_PRICE_INCREASE_DENOMINATOR,
	RANDOMWALK_NFT_WITHDRAWAL_WAIT_SECONDS,
};
